"""empty message

Revision ID: bcb5947d9990
Revises:
Create Date: 2023-04-29 07:19:30.302440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

# here we use the same revision as was in alembic_version table as root revision
revision = '13312e0d4950'

down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###