"""create Profile table

Revision ID: 13312e0d4950
Revises: d2c45bf2a36f
Create Date: 2023-04-29 06:19:52.056942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13312e0d4950'
down_revision = 'd2c45bf2a36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('linkidln_link', sa.String(), nullable=True),
    sa.Column('facebook_link', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_profiles_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index('idx_profiles_user_id', ['user_id'], unique=False)

    op.drop_table('network')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('C1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('C2', sa.TEXT(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_profiles_user_id')

    op.drop_table('profiles')
    # ### end Alembic commands ###
