"""empty message

Revision ID: 1798d1f0c823
Revises: bcb5947d9990
Create Date: 2023-05-05 23:16:19.717051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1798d1f0c823'
down_revision = 'bcb5947d9990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
