"""change back

Revision ID: c7b1432c2082
Revises: 22a458aa66a1
Create Date: 2023-04-10 01:19:04.613095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b1432c2082'
down_revision = '22a458aa66a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.drop_column('passw')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passw', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
